/*
    QUERY DE CRIAÇÃO DAS TABELAS DA BASE DE DADOS
    BASE DE DADOS: PHARMA_MANAGER
    DATA: 30/12/2025
    ORDEM CORRIGIDA PARA INTEGRIDADE REFERENCIAL
*/


-- ==========================================================
-- 1. TABELAS SEM DEPENDÊNCIAS (NÍVEL 0)
-- ==========================================================

-- DROP DATABASE PHARMA_MANAGER;
-- CREATE DATABASE PHARMA_MANAGER;
-- USE PHARMA_MANAGER;

CREATE TABLE TB_USUARIO (
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    SENHA NVARCHAR(200) NOT NULL,
    ATIVO BIT DEFAULT 1
);

CREATE TABLE TB_CARGO (
    ID_CARGO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(50) NOT NULL,
    DESCRICAO NVARCHAR(200),
    ATIVO BIT DEFAULT 1
);

CREATE TABLE TB_PROVINCIA (
    ID_PROVINCIA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(100) NOT NULL
);

CREATE TABLE TB_PERMISSAO (
    ID_PERMISSAO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(50) NOT NULL
);

CREATE TABLE TB_CLIENTE (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(250) NOT NULL,
    TELEFONE VARCHAR(20)
);

CREATE TABLE TB_CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(100) NOT NULL,
    ATIVO BIT DEFAULT 1
);

CREATE TABLE TB_METODO_PAGAMENTO (
    ID_METODO_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(30) NOT NULL,
    ATIVO BIT DEFAULT 1
);

CREATE TABLE TB_ESTADO_FATURA (
    ID_ESTADO_FATURA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(30) NOT NULL UNIQUE
);

-- ==========================================================
-- 2. TABELAS COM DEPENDÊNCIAS NÍVEL 1 (LOCALIZAÇÃO E ACESSO)
-- ==========================================================

CREATE TABLE TB_MUNICIPIO (
    ID_MUNICIPIO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(100) NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES TB_PROVINCIA(ID_PROVINCIA)
);

CREATE TABLE TB_USUARIO_PERMISSAO (
    ID_USUARIO INT NOT NULL,
    ID_PERMISSAO INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_PERMISSAO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PERMISSAO) REFERENCES TB_PERMISSAO(ID_PERMISSAO)
);

CREATE TABLE TB_PRODUTO (
    ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(150) NOT NULL,
    CODIGO_BARRAS VARCHAR(30) UNIQUE NOT NULL,
    PRECO_VENDA DECIMAL(18,2) NOT NULL,
    ID_CATEGORIA INT,
    DATA_CRIACAO DATETIME DEFAULT GETDATE(),
    ATIVO BIT DEFAULT 1,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA)
);

-- ==========================================================
-- 3. TABELAS DE ENDEREÇO E ENTIDADES (FUNCIONÁRIO/FORNECEDOR)
-- ==========================================================

CREATE TABLE TB_ENDERECO (
    ID_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
    BAIRRO NVARCHAR(100),
    ID_MUNICIPIO INT NOT NULL,
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES TB_MUNICIPIO(ID_MUNICIPIO)
);

CREATE TABLE TB_FUNCIONARIO (
    ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(250) NOT NULL,
    BILHETE_IDENTIDADE VARCHAR(20) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL,
    ID_USUARIO INT,
    ID_CARGO INT NOT NULL,
    ID_ENDERECO INT,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(150),
    ATIVO BIT DEFAULT 1,
    FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO),
    FOREIGN KEY (ID_CARGO) REFERENCES TB_CARGO(ID_CARGO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_FORNECEDOR (
    ID_FORNECEDOR INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(250) NOT NULL,
    NIF VARCHAR(25) UNIQUE,
    ID_ENDERECO INT,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(150),
    ATIVO BIT DEFAULT 1,
    FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO)
);

-- ==========================================================
-- 4. VENDAS E ESTOQUE (FATURAMENTO)
-- ==========================================================

CREATE TABLE TB_FATURA (
    ID_FATURA INT PRIMARY KEY IDENTITY(1,1),
    ID_CLIENTE INT,
    ID_FUNCIONARIO INT NOT NULL,
    ID_ESTADO_FATURA INT NOT NULL,
    ID_METODO_PAGAMENTO INT NOT NULL,
    DATA_VENDA DATETIME DEFAULT GETDATE(),
    ATIVO BIT DEFAULT 1,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_METODO_PAGAMENTO) REFERENCES TB_METODO_PAGAMENTO(ID_METODO_PAGAMENTO),
    FOREIGN KEY (ID_ESTADO_FATURA) REFERENCES TB_ESTADO_FATURA(ID_ESTADO_FATURA)
);

CREATE TABLE TB_ITEM_FATURA (
    ID_FATURA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_VENDA DECIMAL(18,2) NOT NULL,
    DESCONTO DECIMAL(18,2) DEFAULT 0,
    TAXA_IMPOSTO DECIMAL(18,2) DEFAULT 14,
    PRIMARY KEY (ID_FATURA, ID_PRODUTO),
    FOREIGN KEY (ID_FATURA) REFERENCES TB_FATURA(ID_FATURA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
);

-- ==========================================================
-- 5. MOVIMENTAÇÃO DE ESTOQUE E LOTES
-- ==========================================================

CREATE TABLE TB_LOTE (
    ID_LOTE INT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    DATA_VALIDADE DATE NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDOR(ID_FORNECEDOR),
    UNIQUE(ID_LOTE, ID_PRODUTO)
);

CREATE TABLE TB_ESTOQUE (
    ID_ESTOQUE INT PRIMARY KEY IDENTITY(1,1),
    ID_LOTE INT NOT NULL,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE >= 0),
    DATA_CRIACAO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_LOTE) REFERENCES TB_LOTE(ID_LOTE)
);

CREATE TABLE TB_MOVIMENTO_ESTOQUE (
    ID_MOVIMENTO INT PRIMARY KEY IDENTITY(1, 1),
    TIPO NVARCHAR(50) NOT NULL, -- Entrada, Saída, Ajuste
    MOTIVO NVARCHAR(MAX),
    DATA_MOVIMENTO DATETIME DEFAULT GETDATE(),
    ID_FUNCIONARIO INT NOT NULL,
    ID_FATURA INT,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (ID_FUNCIONARIO),
    FOREIGN KEY (ID_FATURA) REFERENCES TB_FATURA (ID_FATURA)
);

CREATE TABLE TB_DETALHES_MOVIMENTO_ESTOQUE (
    ID_DETALHE_MOVIMENTO INT PRIMARY KEY IDENTITY(1, 1),
    ID_MOVIMENTO INT NOT NULL,
    QUANTIDADE_ANTERIOR INT,
    QUANTIDADE_ATUAL INT,
    ID_LOTE INT,
    FOREIGN KEY (ID_MOVIMENTO) REFERENCES TB_MOVIMENTO_ESTOQUE (ID_MOVIMENTO),
    FOREIGN KEY (ID_LOTE) REFERENCES TB_LOTE (ID_LOTE)
);


INSERT INTO TB_PROVINCIA (NOME) VALUES
('Cubango'),
('Namibe'),
('Cunene'),
('Huíla'),
('Benguela'),
('Cuanza-Norte'),
('Cuanza-Sul'),
('Huambo'),
('Cuando'),
('Moxico'),
('Moxico Leste'),
('Malanje'),
('Cabinda'),
('Zaire'),
('Uíge'),
('Bengo'),
('Lunda-Norte'),
('Lunda-Sul'),
('Bié'),
('Icolo e Bengo'),
('Luanda');



INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Caiundo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Calai', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Chinguanja', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Cuangar', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Cuchi', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Cutato', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Longa', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Mavengue', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Menongue', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Nancova', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Savate', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Moçâmedes', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Bibala', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Virei', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Camucuio', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Tômbua', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Lucira', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Iona', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Sacomar', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Cacimbas', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Canhama', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Cuanhama', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Curoca', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Cuvelai', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Namacunde', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Ombadja', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Chiéde', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Neome', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Humbe', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Mupa', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Naulila', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Chitado', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Cafima', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Chissuata', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Lubango', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Cacula', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Calaquembe', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chibia', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chicomba', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chipindo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Gambos', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Cuvango', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Humpata', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Jamba Mineira', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Quilengues', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Matala', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Dongo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Hoque', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Capelogo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Capunda Cavilongo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Viti Vivili', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Galangue', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Palanca', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chicungo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
VALUES 
('Baía Farta', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Balombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Bocoio', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Caimbambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Catumbela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chongorói', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Cubal', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Ganda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Lobito', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Benguela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Egito Praia', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chindumbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Dombe Grande', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Capupa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Biópio', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chila', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chicuma', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Babaera', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Iambala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Catengue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Bolonguera', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Canhamela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Navegantes', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela'));



-- Municípios de Cuanza-Norte
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Ambaca', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Banga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Bolongongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Cambambe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Cazengo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Golungo Alto', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Lucala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Ngonguembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Quiculungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Samba Cajú', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Massangano', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Cêrça', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Tango', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Terreiro', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Aldeia Nova', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Caculo Cabaça', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Luinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte'));

-- Municípios de Cuanza-Sul
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Gabela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Cassongue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Waku Kungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Conda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Ebo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Calulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Mussende', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Porto Amboim', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quibala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quilenda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Seles', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Sumbe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quirimbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Munenga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quissongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Gungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Sanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Gangula', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Pambangala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Condé', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Amboiva', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Lonhe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quenha', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Boa Entrada', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul'));



-- Municípios de Huambo
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cuito Cuanavale', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Dirico', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Mavinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Rivungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Xipundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Dima', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Luiana', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Mucusso', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Luengue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo'));

-- Municípios de Cuando
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Bailundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Caála', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Cachiungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Chicala Choloanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Chinjenje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Ecunha', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Huambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Londuimbali', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Longonjo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Mungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Ucuma', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Bimbe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Sambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Galanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Alto Hama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Chilata', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Cuima', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando'));





-- Municípios de Moxico
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Chiúme', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lumbala Nguimbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Camanongue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Léua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Alto Cuito', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lutembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Cangumbe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Luena', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Cangamba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lucusse', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Ninda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lutuai', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico'));

-- Municípios de Moxico Leste
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cazombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Luacano', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Cameia', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Luau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Nana Candundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Macondo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Caianda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Lóvua do Zambeze', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Lago Dilolo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste'));

-- Municípios de Malanje
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cacuso', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cahombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Calandula', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cambundi Catembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cangandala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Kiwaba Nzoji', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Kunda dya Baze', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Luquembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Malanje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Marimba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Massango', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quirima', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cateco Cangola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cuale', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Pungo a Ndongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Ngola Luiji', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quihuhu', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Xandel', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cambo Suinginge', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Milando', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quitapa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Capunda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Muquixe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quêssua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Caculama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Mbanji ya Ngola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje'));




-- Municípios de Cabinda
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Belize', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Buco-Zau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Cabinda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Cacongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Miconje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Massabi', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Necuto', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Tando Zinze', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Liambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Ngoio', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda'));

-- Municípios de Zaire
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Mbanza Kongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Soyo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Nzeto', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Cuimba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Nóqui', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Tomboco', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Luvo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Lufico', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Quêlo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Serra de Canda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Quindeje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire'));

-- Municípios de Uíge
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Uíge', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Cangola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Ambuíla', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Bembe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Nova Esperança', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Bungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Milunga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Damba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Maquela do Zombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Mucaba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Negage', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Puri', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Quimbele', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Dange Qitexe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Sanza Pombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Songo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Sacandica', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Nsosso', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Lucunga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Quipedro', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Massau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Vista Alegre', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Alto Zaza', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge'));




-- Municípios de Bengo
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Bula Atumba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Dande', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Quibaxe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Nambuangongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Pango Aluquém', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Ambriz', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Muxaluando', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Piri', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Quicunzo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Úcua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Panguila', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Barra do Dande', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo'));

-- Municípios de Lunda-Norte
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cámbulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Capenda Camulemba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Caungula', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Chitato', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cuan', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cuílo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Lubalo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Lucapa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Lóvua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Xá-Muteba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Dundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Xá Cassau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Camaxilo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Luangue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Luremo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Canzar', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cassanje Calucala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Mussungue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cafunfu', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte'));

-- Municípios de Lunda-Sul
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cacolo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Dala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Muconda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Saurimo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Chiluage', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Cassai-Sul', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Xassengue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Alto Chicapa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Sombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Muriege', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Luma Cassai', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Cazage', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Muangueji', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Cassengo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul'));



-- Municípios de Bié
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Andulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Camacupa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Catabola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chinguar', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chitembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cuemba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cuito', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cunhinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Nharêa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Luando', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Ringoma', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Mumbué', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Calucinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chicala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chipeta', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Umpulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Lúbia', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cambândua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Belo Horizonte', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié'));

-- Municípios de Luanda
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Belas', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Cacuaco', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Cazenga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Kilamba Kiaxi', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Viana', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Mussulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Sambizanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Rangel', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Maianga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Samba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Camama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Mulenvos', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Kilamba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Hoji Ya Henda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Ingombota', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Talatona', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda'));



-- Municípios de Icolo e Bengo
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Catete', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Quiçama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Calumbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Cabiri', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Cabo Ledo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Bom Jesus', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Sequele', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo'));



-- Permitir inserção manual do ID
SET IDENTITY_INSERT TB_ENDERECO ON;

INSERT INTO TB_ENDERECO (ID_ENDERECO, BAIRRO, ID_MUNICIPIO) VALUES
(1,  'Maianga',        21),
(2,  'Alvalade',       21),
(3,  'Samba',          21),
(4,  'Kilamba',        21),
(5,  'Talatona',       21),
(6,  'Benfica',        21),
(7,  'Cazenga',        21),
(8,  'Viana',          21),
(9,  'Zango',          21),
(10, 'Mutamba',        21),
(11, 'Rangel',         21),
(12, 'Golf 2',         21),
(13, 'Camama',         21),
(14, 'Patriota',       21),
(15, 'Hoji-Ya-Henda',  21);

-- Desativar inserção manual do ID
SET IDENTITY_INSERT TB_ENDERECO OFF;


/*
==============================
CRIAR USUARIOS PREDEFINIDOS
==============================
*/
SET IDENTITY_INSERT TB_USUARIO ON;

INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA) VALUES
(1, 'evaney@pharma.com', '123'),
(2, 'dnp@pharma.com', '123'),
(3, 'aristides@pharma.com', '123'),
(4, 'severina@pharma.com', '123'),
(5, 'gelson@pharma.com', '123');

SET IDENTITY_INSERT TB_USUARIO OFF;


/*
==============================
CRIAR CARGOS PREDEFINIDOS
==============================
*/
INSERT INTO TB_CARGO (NOME, DESCRICAO) VALUES
('Assistente de Farmácia', 'Auxilia nas atividades diárias, atendimento ao cliente e organização de produtos.'),
('Caixa', 'Responsável pelo registro de vendas, recebimento de pagamentos e emissão de faturas.'),
('Farmacêutico', 'Profissional habilitado para prescrição e orientação de medicamentos, controle de qualidade e farmácia clínica.'),
('Estoquista', 'Responsável pelo recebimento, armazenamento e controle de estoque de produtos.'),
('Atendente', 'Atende os clientes no balcão, tira dúvidas e orienta sobre produtos.'),
('Supervisor de Vendas', 'Coordena a equipe de vendas, estabelece metas e acompanha desempenho.'),
('Analista de Compras', 'Responsável por negociação com fornecedores, reposição de produtos e análise de preços.'),
('Marketing', 'Desenvolve campanhas promocionais e ações de divulgação da farmácia.'),
('Segurança', 'Responsável pela segurança do estabelecimento, clientes e funcionários.');


/*
==============================
CRIAR FUNCIONARIOS PREDEFINIDOS
==============================
*/
INSERT INTO TB_FUNCIONARIO
(NOME, BILHETE_IDENTIDADE, DATA_NASCIMENTO, ID_USUARIO, ID_CARGO, ID_ENDERECO, TELEFONE, EMAIL)
VALUES
('Evaney Francisco Matadi Gonçalo', '123456789LA001', '1985-03-12', 1, 1, 1, '912345678', 'evaney@pharma.com'),
('Domingos Nkula Pedro', '234567890LU002', '1990-07-21', 2, 2, 2, '923456789', 'dnp@pharma.com'),
('Aristides Muhongo Félix', '345678901BE003', '1982-11-05', 3, 3, 3, '934567890', 'aristides@pharma.com'),
('Severina Arão Elísio', '456789012HU004', '1988-01-18', 4, 4, 4, '945678901', 'severina@pharma.com'),
('Gelson Antonio Clemente', '567890123CA005', '1995-06-30', 5, 5, 5, '956789012', 'gelson@pharma.com');


/*
==============================
CRIAR PERMISSOES
==============================
*/
INSERT INTO TB_PERMISSAO (NOME) VALUES
('Administrador'),
('Caixa');


/*
==============================
ATRIBUIR PERMISSOES AOS USUARIOS
==============================
*/
INSERT INTO TB_USUARIO_PERMISSAO (ID_USUARIO, ID_PERMISSAO) VALUES
-- Evaney 
(1,2),
-- Domingos 
(2,2),
-- Aristides
(3,2),
-- Severina (Admin)
(4,1),
-- Gelson
(5,2);

/*
==============================
CRIAR FORNECEDORES
==============================
*/
SET IDENTITY_INSERT TB_FORNECEDOR ON;

INSERT INTO TB_FORNECEDOR (ID_FORNECEDOR, NOME, NIF, ID_ENDERECO, TELEFONE, EMAIL) VALUES
(1, 'Farmaco Distribuidora', '123456789', 6, '912345678', 'contato@farmacodistribuidora.com'),
(2, 'Saúde Total', '987654321', 7, '923456789', 'vendas@saudetotal.com'),
(3, 'Distribuidora Central', '456789123', 8, '934567890', 'info@distribuidoracentral.com'),
(4, 'Medicorp', '789123456', 9, '945678901', 'contato@medicorp.com'),
(5, 'BioFarm', '321654987', 10, '956789012', 'vendas@biofarm.com'),
(6, 'Farmalider', '654987321', 11, '967890123', 'suporte@farmalider.com'),
(7, 'MedHealth', '147258369', 12, '978901234', 'contato@medhealth.com'),
(8, 'Distribuidora Vida', '258369147', 13, '989012345', 'info@distribuidoravida.com'),
(9, 'Saúde e Bem', '369147258', 14, '991234567', 'vendas@saudeebem.com'),
(10,'Pharma Supplies', '159357486', 15, '902345678', 'contato@pharmasupplies.com');

SET IDENTITY_INSERT TB_FORNECEDOR OFF;


/*
==============================
CRIAR CATEGORIAS
==============================
*/
SET IDENTITY_INSERT TB_CATEGORIA ON;

INSERT INTO TB_CATEGORIA (ID_CATEGORIA, NOME) VALUES
(1,'Medicamentos Genéricos'),
(2,'Medicamentos de Marca'),
(3,'Suplementos Alimentares'),
(4,'Vitaminas e Minerais'),
(5,'Produtos de Higiene'),
(6,'Produtos de Beleza'),
(7,'Materiais de Curativo'),
(8,'Equipamentos Médicos'),
(9,'Infantis e Bebês'),
(10,'Produtos Naturais'),
(11,'Medicamentos Isentos de Prescrição'),
(12,'Produtos Ortopédicos'),
(13,'Produtos para Saúde Sexual'),
(14,'Produtos para Diabéticos'),
(15,'Produtos de Higiene Oral');

SET IDENTITY_INSERT TB_CATEGORIA OFF;


/*
==============================
CRIAR PRODUTOS
==============================
*/

SET IDENTITY_INSERT TB_PRODUTO ON;

INSERT INTO TB_PRODUTO
(ID_PRODUTO, NOME, CODIGO_BARRAS, PRECO_VENDA, ID_CATEGORIA, DATA_CRIACAO)
VALUES
(1,'Paracetamol 500mg','789100000001',1200.00,1,GETDATE()),
(2,'Ibuprofeno 400mg','789100000002',2500.00,1,GETDATE()),
(3,'Vitamina C 1000mg','789100000003',4500.00,4,GETDATE()),
(4,'Suplemento Multivitamínico','789100000004',12500.00,3,GETDATE()),
(5,'Creme Hidratante','789100000005',8500.00,6,GETDATE()),
(6,'Fralda Infantil P','789100000006',9500.00,9,GETDATE()),
(7,'Álcool Gel 70%','789100000007',1500.00,5,GETDATE()),
(8,'Máscara Cirúrgica','789100000008',150.00,8,GETDATE()),
(9,'Pomada Antisséptica','789100000009',3500.00,7,GETDATE()),
(10,'Chá Natural Relaxante','789100000010',2800.00,10,GETDATE()),
(11,'Antiácido Mastigável','789100000011',2200.00,11,GETDATE()),
(12,'Joelheira Ortopédica','789100000012',18500.00,12,GETDATE()),
(13,'Preservativo Masculino','789100000013',1200.00,13,GETDATE()),
(14,'Glicosímetro Digital','789100000014',32000.00,14,GETDATE()),
(15,'Pasta Dental Medicinal','789100000015',1800.00,15,GETDATE());

SET IDENTITY_INSERT TB_PRODUTO OFF;


/*
==============================
CRIAR LOTES
==============================
*/

INSERT INTO TB_LOTE
(ID_LOTE, ID_PRODUTO, ID_FORNECEDOR, DATA_VALIDADE)
VALUES
(1,1,1,'2026-12-31'),
(2,2,2,'2029-11-30'),
(3,3,3,'2027-01-15'),
(4,4,4,'2026-08-20'),
(5,5,5,'2026-10-10'),
(6,6,6,'2028-12-31'),
(7,7,7,'2026-06-30'),
(8,8,8,'2027-09-30'),
(9,9,9,'2026-03-15'),
(10,10,10,'2026-12-31');

/*
==============================
CRIAR ESTOQUE
==============================
*/
SET IDENTITY_INSERT TB_ESTOQUE ON;

INSERT INTO TB_ESTOQUE
(ID_ESTOQUE, ID_LOTE, QUANTIDADE, DATA_CRIACAO)
VALUES
(1,1,100,GETDATE()),
(2,2,150,GETDATE()),
(3,3,200,GETDATE()),
(4,4,120,GETDATE()),
(5,5,80,GETDATE()),
(6,6,50,GETDATE()),
(7,7,300,GETDATE()),
(8,8,500,GETDATE()),
(9,9,60,GETDATE()),
(10,10,90,GETDATE());

SET IDENTITY_INSERT TB_ESTOQUE OFF;


/*
==============================
METODOS DE PAGAMENTO
==============================
*/
SET IDENTITY_INSERT TB_METODO_PAGAMENTO ON;

INSERT INTO TB_METODO_PAGAMENTO (ID_METODO_PAGAMENTO, NOME) VALUES
(1,'Dinheiro'),
(2,'Multicaixa'),
(3,'Multicaixa Express'),
(4,'Transferência Bancária'),
(5,'Mobile Money'),
(6,'Cartão de Débito Internacional'),
(7,'Cartão de Crédito'),
(8,'Pagamento por Referência'),
(9,'Carteira Digital'),
(10,'Outro');

SET IDENTITY_INSERT TB_METODO_PAGAMENTO OFF;


/*
==============================
ESTADOS DA FATURA
==============================
*/
SET IDENTITY_INSERT TB_ESTADO_FATURA ON;

INSERT INTO TB_ESTADO_FATURA (ID_ESTADO_FATURA, NOME) VALUES
(1,'Pendente'),
(2,'Pago'),
(3,'Cancelada');

SET IDENTITY_INSERT TB_ESTADO_FATURA OFF;

