INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Caiundo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Calai', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Chinguanja', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Cuangar', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Cuchi', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Cutato', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Longa', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Mavengue', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Menongue', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Nancova', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango'
UNION ALL SELECT 'Savate', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cubango';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Moçâmedes', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Bibala', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Virei', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Camucuio', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Tômbua', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Lucira', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Iona', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Sacomar', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe'
UNION ALL SELECT 'Cacimbas', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Namibe';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Canhama', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Cuanhama', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Curoca', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Cuvelai', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Namacunde', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Ombadja', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Chiéde', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Neome', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Humbe', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Mupa', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Naulila', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Chitado', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Cafima', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene'
UNION ALL SELECT 'Chissuata', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cunene';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
SELECT 'Lubango', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Cacula', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Calaquembe', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chibia', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chicomba', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chipindo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Gambos', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Cuvango', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Humpata', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Jamba Mineira', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Quilengues', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Matala', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Dongo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Hoque', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Capelogo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Capunda Cavilongo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Viti Vivili', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Galangue', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Palanca', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla'
UNION ALL SELECT 'Chicungo', ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huíla';


INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA)
VALUES 
('Baía Farta', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Balombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Bocoio', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Caimbambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Catumbela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chongorói', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Cubal', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Ganda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Lobito', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Benguela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Egito Praia', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chindumbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Dombe Grande', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Capupa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Biópio', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chila', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Chicuma', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Babaera', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Iambala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Catengue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Bolonguera', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Canhamela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela')),
('Navegantes', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Benguela'));



-- Municípios de Cuanza-Norte
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Ambaca', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Banga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Bolongongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Cambambe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Cazengo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Golungo Alto', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Lucala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Ngonguembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Quiculungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Samba Cajú', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Massangano', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Cêrça', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Tango', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Terreiro', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Aldeia Nova', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Caculo Cabaça', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte')),
('Luinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Norte'));

-- Municípios de Cuanza-Sul
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Gabela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Cassongue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Waku Kungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Conda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Ebo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Calulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Mussende', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Porto Amboim', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quibala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quilenda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Seles', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Sumbe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quirimbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Munenga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quissongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Gungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Sanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Gangula', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Pambangala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Condé', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Amboiva', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Lonhe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Quenha', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul')),
('Boa Entrada', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuanza-Sul'));



-- Municípios de Huambo
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cuito Cuanavale', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Dirico', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Mavinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Rivungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Xipundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Dima', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Luiana', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Mucusso', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo')),
('Luengue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Huambo'));

-- Municípios de Cuando
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Bailundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Caála', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Cachiungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Chicala Choloanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Chinjenje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Ecunha', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Huambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Londuimbali', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Longonjo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Mungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Ucuma', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Bimbe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Sambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Galanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Alto Hama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Chilata', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando')),
('Cuima', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cuando'));





-- Municípios de Moxico
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Chiúme', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lumbala Nguimbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Camanongue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Léua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Alto Cuito', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lutembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Cangumbe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Luena', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Cangamba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lucusse', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Ninda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico')),
('Lutuai', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico'));

-- Municípios de Moxico Leste
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cazombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Luacano', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Cameia', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Luau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Nana Candundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Macondo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Caianda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Lóvua do Zambeze', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste')),
('Lago Dilolo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Moxico Leste'));

-- Municípios de Malanje
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cacuso', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cahombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Calandula', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cambundi Catembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cangandala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Kiwaba Nzoji', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Kunda dya Baze', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Luquembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Malanje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Marimba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Massango', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quela', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quirima', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cateco Cangola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cuale', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Pungo a Ndongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Ngola Luiji', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quihuhu', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Xandel', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Cambo Suinginge', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Milando', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quitapa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Capunda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Muquixe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Quêssua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Caculama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje')),
('Mbanji ya Ngola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Malanje'));




-- Municípios de Cabinda
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Belize', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Buco-Zau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Cabinda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Cacongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Miconje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Massabi', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Necuto', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Tando Zinze', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Liambo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda')),
('Ngoio', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Cabinda'));

-- Municípios de Zaire
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Mbanza Kongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Soyo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Nzeto', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Cuimba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Nóqui', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Tomboco', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Luvo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Lufico', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Quêlo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Serra de Canda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire')),
('Quindeje', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Zaire'));

-- Municípios de Uíge
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Uíge', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Cangola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Ambuíla', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Bembe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Nova Esperança', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Bungo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Milunga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Damba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Maquela do Zombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Mucaba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Negage', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Puri', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Quimbele', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Dange Qitexe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Sanza Pombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Songo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Sacandica', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Nsosso', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Lucunga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Quipedro', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Massau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Vista Alegre', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge')),
('Alto Zaza', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Uíge'));




-- Municípios de Bengo
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Bula Atumba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Dande', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Quibaxe', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Nambuangongo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Pango Aluquém', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Ambriz', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Muxaluando', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Piri', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Quicunzo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Úcua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Panguila', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo')),
('Barra do Dande', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bengo'));

-- Municípios de Lunda-Norte
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cámbulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Capenda Camulemba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Caungula', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Chitato', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cuan', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cuílo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Lubalo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Lucapa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Lóvua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Xá-Muteba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Dundo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Xá Cassau', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Camaxilo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Luangue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Luremo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Canzar', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cassanje Calucala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Mussungue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte')),
('Cafunfu', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Norte'));

-- Municípios de Lunda-Sul
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Cacolo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Dala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Muconda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Saurimo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Chiluage', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Cassai-Sul', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Xassengue', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Alto Chicapa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Sombo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Muriege', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Luma Cassai', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Cazage', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Muangueji', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul')),
('Cassengo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Lunda-Sul'));



-- Municípios de Bié
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Andulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Camacupa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Catabola', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chinguar', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chitembo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cuemba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cuito', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cunhinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Nharêa', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Luando', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Ringoma', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Mumbué', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Calucinga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chicala', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Chipeta', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Umpulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Lúbia', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Cambândua', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié')),
('Belo Horizonte', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Bié'));

-- Municípios de Luanda
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Belas', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Cacuaco', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Cazenga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Kilamba Kiaxi', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Viana', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Mussulo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Sambizanga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Rangel', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Maianga', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Samba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Camama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Mulenvos', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Kilamba', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Hoji Ya Henda', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Ingombota', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda')),
('Talatona', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Luanda'));



-- Municípios de Icolo e Bengo
INSERT INTO TB_MUNICIPIO (NOME, ID_PROVINCIA) VALUES
('Catete', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Quiçama', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Calumbo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Cabiri', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Cabo Ledo', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Bom Jesus', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo')),
('Sequele', (SELECT ID_PROVINCIA FROM TB_PROVINCIA WHERE NOME = 'Icolo e Bengo'));