/*

    QUERY DE CRIAÇÃO DAS TABELAS DA BASE DE DADOS
    BASE DE DADOS: PHARMA_MANAGER
    DATA: 05/12/2025
    AUTORES: ARISTIDES MUHONGO, SEVERINA ELÍSIO, DNP

*/


CREATE TABLE TB_USUARIO
(
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    SENHA NVARCHAR(200) NOT NULL,
    FOTO NVARCHAR (MAX)
)

  
CREATE TABLE TB_CARGO
(
    ID_CARGO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(50) NOT NULL,
    DESCRICAO NVARCHAR (200)
)

  
CREATE TABLE TB_PROVINCIA
(
    ID_PROVINCIA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(100) NOT NULL
)

  
CREATE TABLE TB_MUNICIPIO
(
    ID_MUNICIPIO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(100) NOT NULL,
    
    ID_PROVINCIA INT NOT NULL,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES TB_PROVINCIA(ID_PROVINCIA)
)

  
CREATE TABLE TB_ENDERECO
(
    ID_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
    BAIRRO NVARCHAR(100),
    RUA NVARCHAR(100),
    CASA NVARCHAR(100),
    ID_MUNICIPIO INT NOT NULL,
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES TB_MUNICIPIO(ID_MUNICIPIO)
)


CREATE TABLE TB_FUNCIONARIO
(
    ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(250) NOT NULL,
    BILHETE_IDENTIDADE VARCHAR(20) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL,
    ID_USUARIO INT,
    ID_CARGO INT NOT NULL,
    ID_ENDERECO INT,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(150),

    FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO),
    FOREIGN KEY (ID_CARGO) REFERENCES TB_CARGO(ID_CARGO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
)

  
CREATE TABLE TB_PERMISSAO
(
    ID_PERMISSAO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(50) NOT NULL
)
  

CREATE TABLE TB_USUARIO_PERMISSAO
(
    ID_USUARIO INT NOT NULL,
    ID_PERMISSAO INT NOT NULL,

    PRIMARY KEY (ID_USUARIO, ID_PERMISSAO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PERMISSAO) REFERENCES TB_PERMISSAO(ID_PERMISSAO)
)

  
CREATE TABLE TB_FORNECEDOR
(
    ID_FORNECEDOR INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(250) NOT NULL,
    NIF VARCHAR(25) UNIQUE,
    ID_ENDERECO INT,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(150),
    ATIVO BIT DEFAULT 1,

    FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO)
)


CREATE TABLE TB_CLIENTE
(
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(250) NOT NULL,
    TELEFONE VARCHAR(20)
)

/*
=========== PRODUTOS
*/


CREATE TABLE TB_CATEGORIA
(
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(100) NOT NULL
)


CREATE TABLE TB_PRODUTO
(
    ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(150) NOT NULL,
    CODIGO_BARRAS VARCHAR(30) UNIQUE NOT NULL,
    PRECO_VENDA DECIMAL(18,2) NOT NULL,
    ID_CATEGORIA INT,
    DATA_CRIACAO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA)
)


CREATE TABLE TB_LOTE
(
    ID_LOTE INT PRIMARY KEY IDENTITY(1,1),
    ID_PRODUTO INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    DATA_VALIDADE DATE NOT NULL,
    PRECO_COMPRA DECIMAL(18,2) NOT NULL,

    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDOR(ID_FORNECEDOR)
)


CREATE TABLE TB_ESTOQUE
(
    ID_ESTOQUE INT PRIMARY KEY IDENTITY(1,1),
    ID_LOTE INT NOT NULL,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE >= 0),
    DATA_CRIACAO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_LOTE) REFERENCES TB_LOTE(ID_LOTE)
)


CREATE TABLE TB_MOVIMENTO_ESTOQUE
(
    ID_MOVIMENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_LOTE INT NOT NULL,
    TIPO NVARCHAR(15) NOT NULL, -- ENTRADA / SAIDA / AJUSTE
    QUANTIDADE INT NOT NULL,
    MOTIVO NVARCHAR(MAX),
    DATA_MOVIMENTO DATETIME DEFAULT GETDATE(),
    ID_FUNCIONARIO INT NOT NULL,

    FOREIGN KEY (ID_LOTE) REFERENCES TB_LOTE(ID_LOTE),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO)
)

  
CREATE TABLE TB_METODO_PAGAMENTO
(
    ID_METODO_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(30) NOT NULL
)

  
CREATE TABLE TB_ESTADO_FATURA
(
    ID_ESTADO_FATURA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(30) NOT NULL UNIQUE
)

  
CREATE TABLE TB_FATURA
(
    ID_FATURA INT PRIMARY KEY IDENTITY(1,1),
    ID_CLIENTE INT,
    ID_FUNCIONARIO INT NOT NULL,
    ID_ESTADO_FATURA INT NOT NULL,
    ID_METODO_PAGAMENTO INT NOT NULL,
    DATA_VENDA DATETIME DEFAULT GETDATE(),
    ATIVO BIT DEFAULT 1,

    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_METODO_PAGAMENTO) REFERENCES TB_METODO_PAGAMENTO(ID_METODO_PAGAMENTO),
    FOREIGN KEY (ID_ESTADO_FATURA) REFERENCES TB_ESTADO_FATURA(ID_ESTADO_FATURA)
)


CREATE TABLE TB_ITEM_FATURA
(
    ID_FATURA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
  
    PRECO_VENDA DECIMAL(18,2) NOT NULL,
    DESCONTO DECIMAL(18,2) DEFAULT 0,
    TAXA_IMPOSTO DECIMAL(18,2) DEFAULT 14,

    PRIMARY KEY (ID_FATURA, ID_PRODUTO),
    FOREIGN KEY (ID_FATURA) REFERENCES TB_FATURA(ID_FATURA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
)